# dev version

version: '3.3'
services:
  api:
    image: dangur93/diplom:latest
    container_name: daniil-project-api
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile
    # secrets:
    #   - db_password
    env_file: ./.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./.env
      - ./.db.env
# -----------------------------------------------
  db:
    image: "mysql:8.0.25"
    container_name: "daniil-db"
    # secrets:
    #   - db_password
    ports:
      - "3306:3306"
    volumes:
      - daniil_database:/var/lib/mysql
    env_file: ./.db.env
# -----------------------------------------------
  nginx:
    image: "nginx:1.21.0-alpine"
    container_name: "daniil-project-nginx"
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    logging:
      driver: none

# secrets:
#   db_password:
#     file: ./.db_password.txt

networks:
  default:
    external:
      name: daniil-project-net

volumes:
  daniil_database:
    external: true